name: "Validate PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - reopened

permissions:
  pull-requests: write

jobs:
  lint_pr:
    name: "Call `Validate PR title` shared workflow"
    uses: cumbucadev/shared-workflows/.github/workflows/validate-pr-title-v1.yml@main
